### ISSUE TITLE
Update to user with Subscribe Mobile gets 500

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#102]
As Volunteer or Admin, updating a user with Subscribe Mobile changes gets an error 500.

**Comment by Klaital** [comment]
Looks like this is due to a user setting (or unsetting) the `subscribe_mobile` flag without having a NotificationRegistration first. I've added a check in https://github.com/Klaital/vitasa-web/commit/965ec4bee987152d0f73c83d34faa4defd40a878 so that if the user does not have a registration yet, no error is generated.
