### ISSUE TITLE
SMS not received

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#128]
As admin, sending a notification to any of the groups which includes a user with optin true and that has never logged on from a mobile device, the SMS is not received

**Comment by Klaital** [comment]
Okay, that was a further bundle of worms, hopefully fixed now. The expected workflow for getting sms notifications is simply to update the user with `sms_optin: true`. This should now deregister any existing devices, and subscribe the user to any relevant SNS queues using their saved phone number. 

In order to swap back to push notifications, a user needs to first toggle `sms_optin` back off, then send a new notification_registration for the device they want push notifications on. This code is in staging now.
