### ISSUE TITLE
Text message (and opt-in) if not enabled for notifications

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#56]
For users not using the iOS or Android app, they need to receive notifications through a text message. First we need an opt-in from the user to allow us to send them an SMS, then we need to send a text if they are not registered for the app.

**Comment by Klaital** [comment]
This should actually be supported already, though it hasn't been tested in ages. If you send a NotificationRegistration with platform = 'sms', rather than 'android' or 'apple', it should register the user's phone number that is on file. It will error out if no phone is saved to their profile. We could also gate that registration behind an additional setting, if that's useful.

**Comment by Klaital** [comment]
Right, I had added a field to users for SMS notifications: `sms_optin`. If that is set to true, that should allow users to use their saved phone number for their NotificationRegistration. Calling POST /notification_registrations with `platform='sms'` with `sms_optin` set to false will generate a 400 Bad Request response.
