### ISSUE TITLE
User registration and User Create allows different fields to be set

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#61]
On User Registration: can only set Name, Email, Phone, Password
On User Create by Admin or SuperAdmin: all fields can be set

**Comment by Klaital** [comment]
How do you want to handle Organizations for self-registration? 

For Org Admins, any users they create will automatically belong to their org. For self-registering users, they can either be assigned to the 'null' org (otherwise only populated by the SuperAdmins), or we can let them choose their org.

I vote for either requiring users to supply an Org ID on registration, or simply disallowing self-registration altogether. 

For now, I'm going with Org ID being required.

**Comment by Klaital** [comment]
Implemented in 6e05ac4232bd5728c2d89062eb75ff6d1f614ea5
